---
title: "Analysis of cant estimates"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
params:
  Version_ID: "v_XXX"
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r read_params_local, include = FALSE}

if (params$Version_ID == "v_XXX") {
  params_local <-
    read_rds(here::here("data/auxillary", "params_local.rds"))
  
} else {
  params_local <-
    read_rds(
      file = paste(path_root, "observations",
                   params$Version_ID,
                   "data/params_local.rds",
                   sep = "/")
    )
}

```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")

path_preprocessing_model    <-
  paste(path_root, "/model/preprocessing/", sep = "")

path_version_data     <-
  paste(path_observations,
        params_local$Version_ID,
        "/data/",
        sep = "")

path_version_figures  <-
  paste(path_observations,
        params_local$Version_ID,
        "/figures/",
        sep = "")
```

```{r load_libraries_specific, include = FALSE}

library(purrr)

```


```{r select_basin_mask, include=FALSE}

basinmask <- basinmask %>% 
  filter(MLR_basins == params_local$MLR_basins) %>% 
  select(-c(MLR_basins, basin))

```


# Version ID

The results displayed on this site correspond to the Version_ID: `r params$Version_ID`

# Data sources

Required are: 

- Cant from Sabine 2004 (S04)
- Cant from Gruber 2019 (G19)
- annual mean atmospheric pCO~2~ 

- Mean eMLR-Cant per grid cell (lat, lon, depth)


```{r read_cant_files}


cant_3d_ss <- read_csv(paste(path_version_data,
                             "cant_3d_tref.csv",
                             sep = ""))

cant_3d_emlr <-
  read_csv(paste(path_version_data,
                 "cant_3d.csv",
                 sep = ""))

co2_atm <-
  read_csv(paste(path_preprocessing,
                 "co2_atm.csv",
                 sep = ""))

tref <-
  read_csv(paste(path_version_data,
                 "tref.csv",
                 sep = ""))


cant_3d_model_truth <-
  read_csv(paste(path_version_data,
                 "cant_3d_mod_truth.csv", sep = ""))

```

# Prepare delta Cant

## Steady state

```{r prep_steady_state}

# join with basinmask
cant_3d_ss <- inner_join(cant_3d_ss, basinmask)

# calculate delta cant as the difference between total cant at tref
# this includes the G19 anomaly
cant_3d_ss <- cant_3d_ss %>%
  pivot_wider(names_from = era,
              values_from = "cant_pos") %>% 
  mutate(delta_cant_pos = `2010-2019` - `2000-2009`) %>% 
  select(-c(`2010-2019`, `2000-2009`)) %>% 
  drop_na()


```

## Model truth

```{r prep_model_truth}

cant_3d_model_truth <- cant_3d_model_truth %>% 
  select(lon, lat, depth, basin_AIP, delta_cant_pos = cant_pos) %>% 
  mutate(data_source = "mod_truth")

```

## eMLR(C*)

```{r prep_emlr}

cant_3d_emlr <- cant_3d_emlr %>% 
  select(data_source, lon, lat, depth, basin_AIP, delta_cant_pos = cant_pos)

```

# Join data

## Model

```{r join_mod_data}

cant_3d_mod <- bind_rows(
  cant_3d_emlr %>% filter(data_source == "mod") %>% select(-data_source) %>% mutate(estimate = "emlr"),
  cant_3d_model_truth %>% filter(data_source == "mod_truth") %>% select(-data_source) %>% mutate(estimate = "mod_truth"),
  cant_3d_ss %>% filter(data_source == "mod") %>% select(-data_source) %>% mutate(estimate = "ss")
)

```

## Observations

```{r join_obs_data}

cant_3d_obs <- bind_rows(
  cant_3d_emlr %>% filter(data_source == "obs") %>% select(-data_source) %>% mutate(estimate = "emlr"),
  cant_3d_ss %>% filter(data_source == "obs") %>% select(-data_source) %>% mutate(estimate = "ss")
)

# cant_3d_mod <- cant_3d_mod %>% 
#   pivot_wider(names_from = estimate,
#               values_from = delta_cant_pos)
# 
# cant_3d_mod <- cant_3d_mod %>% 
#   drop_na()

```




# Zonal mean sections

## Model

```{r zonal_section_delta_cant_pos_mod}

# calculate zonal mean section
cant_mod_section <- cant_3d_mod %>%
  group_by(estimate) %>%
  nest() %>%
  mutate(section = map(.x = data, ~m_zonal_mean_sd(.x))) %>%
  select(-data) %>%
  unnest(section)


cant_mod_section_bias <- cant_mod_section %>%
  select(-delta_cant_pos_sd) %>% 
  pivot_wider(names_from = estimate,
              values_from = delta_cant_pos_mean) %>% 
  drop_na()


cant_mod_section_bias <- cant_mod_section_bias %>% 
  mutate(ss_mod_truth = ss -  mod_truth,
         emlr_mod_truth = emlr - mod_truth,
         emlr_ss = emlr - ss) %>% 
  select(-c(emlr:ss))

cant_mod_section_bias_long <- cant_mod_section_bias %>% 
  pivot_longer(ss_mod_truth:emlr_ss,
               values_to = "delta_cant_pos_bias",
               names_to = "estimate")
  

cant_mod_section %>% 
  group_by(basin_AIP, estimate) %>%
  group_split() %>% 
  # head(1) %>% 
  map( ~ p_section_zonal(
    df = .x,
    var = "delta_cant_pos_mean",
    plot_slabs = "n",
    subtitle_text = paste("Basin:", .x$basin_AIP, "| Estimate:", .x$estimate)
  ))

cant_mod_section_bias_long %>% 
  group_by(basin_AIP, estimate) %>%
  group_split() %>% 
  # head(1) %>%
  map( ~ p_section_zonal(
    df = .x,
    var = "delta_cant_pos_bias",
    col = "divergent",
    breaks = params_global$breaks_cant_offset,
    plot_slabs = "n",
    subtitle_text = paste("Basin:", .x$basin_AIP, "| Estimate:", .x$estimate)
  ))

cant_mod_section_bias %>% 
  ggplot(aes(emlr_mod_truth, emlr_ss)) +
  geom_bin2d() +
  scale_fill_viridis_c(trans = "log10") +
  coord_equal() +
  facet_wrap(~ basin_AIP)

cant_mod_section_bias %>% 
  ggplot(aes(emlr_mod_truth, ss_mod_truth)) +
  geom_bin2d() +
  scale_fill_viridis_c(trans = "log10") +
  coord_equal() +
  facet_wrap(~ basin_AIP)

cant_mod_section_bias %>% 
  ggplot(aes(emlr_ss, ss_mod_truth)) +
  geom_bin2d() +
  scale_fill_viridis_c(trans = "log10") +
  coord_equal() +
  facet_wrap(~ basin_AIP)

```

## Observations

```{r zonal_section_delta_cant_pos_obs}

# calculate zonal mean section
cant_obs_section <- cant_3d_obs %>%
  group_by(estimate) %>%
  nest() %>%
  mutate(section = map(.x = data, ~m_zonal_mean_sd(.x))) %>%
  select(-data) %>%
  unnest(section)


cant_obs_section %>% 
  group_by(basin_AIP, estimate) %>%
  group_split() %>% 
  # head(1) %>%
  map( ~ p_section_zonal(
    df = .x,
    var = "delta_cant_pos_mean",
    plot_slabs = "n",
    subtitle_text = paste("Basin:", .x$basin_AIP, "| Estimate:", .x$estimate)
  ))

```
