---
title: "Parameterization"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, include=FALSE}
library(tidyverse)
```


# Definition

The following local parametrisations (i.e. relevant for this sensitivity run) were defined to run the analysis:

```{r define_params_local, class.source = 'fold-show'}

# neutral density thresholds to cut the Atlantic ocean into slabs
slabs_Atl <-
  c(
    -Inf,
    26.00,
    26.50,
    26.75,
    27.00,
    27.25,
    27.50,
    27.75,
    27.85,
    27.95,
    28.05,
    28.10,
    28.15,
    28.20,
    Inf
  )

# neutral density thresholds to cut the Indo-Pacific ocean into slabs
slabs_Ind_Pac <-
  c(-Inf,
    26.00,
    26.50,
    26.75,
    27.00,
    27.25,
    27.50,
    27.75,
    27.85,
    27.95,
    28.05,
    28.10,
    Inf)

# Predictors for MLR model
MLR_predictors <- c(
                "sal",
                "temp",
                "aou",
                "oxygen",
                "phosphate",
                "nitrate",
                "silicate")

# # Transformed predictors for MLR model
# MLR_predictors_trans <- c(
#                 "log(phosphate)")

params_local <-
  lst(
    # ID of current sensitivity run
    Version_ID = "v_XXX",
    # GLODAP version used
    GLODAPv2_version = "2021",
    # f flags accepted for GLODAP data
    flag_f = c(2,9),
    # qc flags accepted for GLODAP data
    flag_qc = c(1),
    # cruises for which calculated tco2 data are accepted
    # even if generally f-flag = 0 data are excluded 
    cruises_tco2_calc = c(
      # "35TH20040604",
      # "29AH20160617"
    ),
    # cruises for which calculated talk data are accepted
    # even if generally f-flag = 0 data are excluded 
    cruises_talk_calc = c(
      "06MT19900123",
      "316N19920502",
      "316N19921006"
    ),
    # additive talk correction for calculate talk data
    talk_calc_corr = 3,
    # cruises for which data with qc = 0 flag are accepted
    # even if generally qc-flag = 0 data are excluded
    cruises_qc_flag = c(
      "31DS19940126"
    ),
    # Shallowest depth for data to be included in MLR fitting
    depth_min = 100, 
    # Depth to extend the surface dcant estimate in mapping
    depth_mapping = 200,
    # Shallowest water depth for data to be included in MLR fitting
    bottomdepth_min = 0,
    # Lowest neutral density to map dcant with eMLR approach
    gamma_min = Inf,
    # CANYON-B offset threshold
    # (factor applied to standard deviation of all cruise offsets)
    CANYON_B_cruise_mean = 2,
    # (factor applied to median of standard deviations of all cruise offsets)
    CANYON_B_sample_SD = 10,
    # minimum sampling depth to apply CANYON-B offset threshold
    CANYON_B_depth = 0,
    # offset correction for cruises expodcode 316N199XXXXX
    cstar_corr_316N199 = 0,
    # offset correction for cruises expodcode 316N199XXXXX
    phosphate_corr_316N199 = 1,
    # offset correction for cruises expodcode 316N199XXXXX
    talk_corr_316N199 = -4,
    # offset correction for cruises expodcode 316N199XXXXX
    tco2_corr_316N199 = 2.5,
    # offset correction for cruises from North Pacific 2010s
    talk_corr_NP_2010 = 2,
    # offset correction for cruises from North Pacific 2010s
    tco2_corr_NP_2010 = -1,
    # threshold for the cruise rmse from a global MLR model of the target variable
    target_global_rmse_max = 1000,
    # start years for eras
    era_start = c(2000, 2010),
    # end years for eras
    era_end = c(2009, 2020),
    # manually define tref1, set to NULL to use median year
    tref1 = 2004,
    # manually define tref2, set to NULL to use median year
    tref2 = 2014,
    # ID for basins for MLR fits (options: "2", "AIP", "5", "SO")
    MLR_basins = "AIP",
    # gap filling of NA values in GLODAP
    gap_filling = "CANYON-B",
    # cruises for which phosphate gaps should be filled with CANYON-B
    cruises_phosphate_gap_fill = c(
      "33MW19930704",
      "33RO20030604",
      "33RO20050111",
      "33RO19980123"
      ),
    
    # cruises for which talk gaps should be filled with CANYON-B
    cruises_talk_gap_fill = c(
      "06AQ19980328"
      ), 
    # cruise adjustment thresholds, not applied when Inf
    cruise_adjustment_relative = Inf, # levels as absolute factor -1
    cruise_adjustment_absolute = Inf, # levels in absolute µM
    # SD of deep water C* values
    cstar_deep_sd = Inf,
    # rarefication approach, options:
    # "coarse_grid" (horizontal 5x5 grid);
    # "reoccupation" (only 1x1 grids sampled in both eras)
    rarefication = "coarse_grid",
    # rarefication approach threshold, quantile of observations with values inside [0,1]
    # 1 is equivalent to no rarefication applied
    rarefication_threshold = 0.95,
    # Select the target variable for MLR, either "tco2", "cstar" or "cstar_tref"
    MLR_target = "cstar_tref",
    # see above
    MLR_predictors = MLR_predictors,
    # # see above
    # MLR_predictors_trans = MLR_predictors_trans,
    # Maxmimum number of MLR predictors
    MLR_predictors_max = 7,
    # Minimum number of MLR predictors
    # (must be at least two, otherwise vif calculation not possible)
    MLR_predictors_min = 2,
    # Total number of MLR fits taken into account
    MLR_number = 10,
    # function used to fit linear regression models: "lm", "rlm"
    MLR_function = "lm",
    # Maximum VIF of fitted MLR models to be included
    vif_max = 500,
    # Criterion to select best MLR fits, either "rmse" or "aic"
    MLR_criterion = "rmse",
    # see above
    slabs_Atl = slabs_Atl,
    # see above
    slabs_Ind_Pac = slabs_Ind_Pac,
    # nutrient for cstar calculation
    cstar_nutrient = "phosphate",
    # Stoichiometric ratio of C to P
    rCP = 117,
    # Stoichiometric ratio of N to P
    rNP = 16,
    # Stoichiometric ratio of P to O (PO4* calculation)
    rPO = 170,
    # Offset P to O (PO4* calculation)
    rPO_offset = 1.95,
    # Preindustrial atmospheric pCO2
    preind_atm_pCO2 = 280,
    # index of slabs to be plotted
    plot_slabs = as.factor(c("(26,26.5]", "(27.5,27.75]", "(27.95,28.05]")),
    # generate a high number of diagnostic plots while running the analysis (y/n)
    plot_all_figures = "n"
  )


```

```{r define_params_local_auto, class.source = 'fold-show', eval=FALSE}

# neutral density thresholds to cut the Atlantic ocean into slabs
slabs_Atl <- lst(
slabs_Atl =
      c(-Inf,
          26.00,
          26.50,
          26.75,
          27.00,
          27.25,
          27.50,
          27.75,
          27.85,
          27.95,
          28.05,
          28.10,
          28.15,
          28.20,
          Inf
        )
      # slabs_Atl =
      # c(-Inf,
      #     26.50,
      #     27.00,
      #     27.50,
      #     27.85,
      #     28.05,
      #     28.15,
      #     Inf
      #   )
      )

# neutral density thresholds to cut the Indo-Pacific ocean into slabs
slabs_Ind_Pac <- lst(
  slabs_Ind_Pac =
    c(
      -Inf,
      26.00,
      26.50,
      26.75,
      27.00,
      27.25,
      27.50,
      27.75,
      27.85,
      27.95,
      28.05,
      28.10,
      Inf
    )
    # slabs_Ind_Pac =
    # c(
    #   -Inf,
    #   26.50,
    #   27.00,
    #   27.50,
    #   27.85,
    #   28.05,
    #   Inf
    # )
)

# Predictors for MLR model
MLR_predictors <- lst(
  MLR_predictors = c("sal", "temp", "aou", "oxygen", "phosphate", "nitrate", "silicate")
  # MLR_predictors = c("temp", "aou", "oxygen", "phosphate", "nitrate", "silicate"),
  # MLR_predictors = c("sal", "aou", "oxygen", "phosphate", "nitrate", "silicate"),
  # MLR_predictors = c("sal", "temp", "oxygen", "phosphate", "nitrate", "silicate"),
  # MLR_predictors = c("sal", "temp", "aou", "phosphate", "nitrate", "silicate"),
  # MLR_predictors = c("sal", "temp", "aou", "oxygen", "nitrate", "silicate"),
  # MLR_predictors = c("sal", "temp", "aou", "oxygen", "phosphate", "silicate"),
  # MLR_predictors = c("sal", "temp", "aou", "oxygen", "phosphate", "nitrate")
  )

# GLODAP version used
GLODAPv2_version = "2021"

# f flags accepted for GLODAP data
flag_f = lst(# flag_f = c(0, 2, 9),
             flag_f = c(2, 9)
             )

# qc flags accepted for GLODAP data
flag_qc = lst(# flag_qc = c(0, 1),
              flag_qc = c(1)
              )

# cruises for which calculated tco2 data are accepted
# even if generally f-flag = 0 data are excluded
cruises_tco2_calc = lst(cruises_tco2_calc =
                          c(
                            # "35TH20040604",
                            # "29AH20160617"
                            ))

# cruises for which calculated talk data are accepted
# even if generally f-flag = 0 data are excluded
cruises_talk_calc = lst(cruises_talk_calc = c(
  "06MT19900123",
  "316N19920502",
  "316N19921006"
  ))

# additive talk correction for calculate talk data
talk_calc_corr = lst(talk_calc_corr = 3)

# cruises for which data with qc = 0 flag are accepted
# even if generally qc-flag = 0 data are excluded
cruises_qc_flag = lst(cruises_qc_flag = c(
  "31DS19940126"
  ))

# Shallowest depth for data to be included in MLR fitting
depth_min = lst(depth_min = 100
                # depth_min = 150
                )
                
# Depth to extend the surface dcant estimate in mapping
depth_mapping = lst(
  depth_mapping = 200
  )

# Shallowest water depth for data to be included in MLR fitting
bottomdepth_min = 0

# Lowest neutral density to map dcant with eMLR approach
gamma_min = lst(
  # gamma_min = 26,
  gamma_min = Inf
)

# CANYON-B offset threshold
# (factor applied to standard deviation of all cruise offsets)
CANYON_B_cruise_mean = lst(
  CANYON_B_cruise_mean = 3
)

# (factor applied to median of standard deviations of all cruise offsets)
CANYON_B_sample_SD = lst(
  CANYON_B_sample_SD = 10
  # CANYON_B_sample_SD = 3,
  # CANYON_B_sample_SD = 2,
  # CANYON_B_sample_SD = 1
)

# minimum sampling depth to apply CANYON-B offset threshold
CANYON_B_depth = 0

# offset correction for cruises expodcode 316N199XXXXX
phosphate_corr_316N199 = 1
# offset correction for cruises expodcode 316N199XXXXX
talk_corr_316N199 = -4
# offset correction for cruises expodcode 316N199XXXXX
tco2_corr_316N199 = 2.5


# offset correction for cruises expodcode 316N199XXXXX
cstar_corr_316N199 = lst(
  cstar_corr_316N199 = 0
)
    

# threshold for the cruise rmse from a global MLR model of the target variable
target_global_rmse_max = lst(
  target_global_rmse_max = 1000
  # target_global_rmse_max = 30,
  # target_global_rmse_max = 20,
  # target_global_rmse_max = 10
)

# start years for eras
era_start = lst(era_start = c(1989, 1999))
era_start = lst(era_start = c(1989, 2010))
era_start = lst(era_start = c(2000, 2010))


# end years for eras
era_end = lst(era_end = c(1998, 2008))
era_end = lst(era_end = c(1999, 2020))
era_end = lst(era_end = c(2009, 2020))

# manually define tref1, set to NULL to use median year
tref1 = 1993
tref1 = 2004

# manually define tref2, set to NULL to use median year
tref2 = 2003
tref2 = 2014

# ID for basins for MLR fits (options: "2", "AIP", "5", "SO")
MLR_basins = lst(
  # MLR_basins = "1",
  # MLR_basins = "2", 
  MLR_basins = "AIP"
  # MLR_basins = "IO_test_lon",
  # MLR_basins = "5",
  # MLR_basins = "SO",
  # MLR_basins = "SO_5",
  # MLR_basins = "SO_AIP",
  # MLR_basins = "SO_2"
)

# gap filling of NA values in GLODAP
gap_filling = lst(
  gap_filling = "CANYON-B"
  # gap_filling = "none"
)


# cruises for which phosphate gaps should be filled with CANYON-B
cruises_phosphate_gap_fill = lst(
  cruises_phosphate_gap_fill = c(
    "33MW19930704",
    "33RO20030604",
    "33RO20050111",
    "33RO19980123"
  )
)

# cruises for which talk gaps should be filled with CANYON-B
cruises_talk_gap_fill = lst(cruises_talk_gap_fill = c(
  "06AQ19980328"
  ))

# cruise adjustment thresholds, not applied when Inf
cruise_adjustment_relative = Inf # levels as absolute factor -1
cruise_adjustment_absolute = Inf # levels in absolute µM

# cstar deep water scatter per station
cstar_deep_sd = lst(
  # cstar_deep_sd = 0.1,
  # cstar_deep_sd = 0.5,
  # cstar_deep_sd = 1,
  # cstar_deep_sd = 2,
  # cstar_deep_sd = 5,
  # cstar_deep_sd = 10,
  cstar_deep_sd = Inf
)

    # rarefication approach, options:
    # "coarse_grid" (horizontal 5x5 grid);
    # "reoccupation" (only 1x1 grids sampled in both eras)
rarefication = "coarse_grid"

# rarefication approach threshold
rarefication_threshold = lst(
  # rarefication_threshold = 1,
  # rarefication_threshold = 0.99,
  rarefication_threshold = 0.95
  # rarefication_threshold = 0.9,
  # rarefication_threshold = 0.75,
  # rarefication_threshold = 0.5
)

# Select the target variable for MLR, either "tco2", "cstar" or "cstar_tref"
MLR_target = lst(
  # MLR_target = "cstar_tref",
  MLR_target = "cstar_tref"
  # MLR_target = "cstar",
  # MLR_target = "cstar_tco2",
  # MLR_target = "cstar_talk",
  # MLR_target = "cstar_phosphate"
)

# Maxmimum number of MLR predictors
MLR_predictors_max = 7

# Minimum number of MLR predictors
MLR_predictors_min = 2

# Total number of MLR fits taken into account
MLR_number = 10

# function used to fit linear regression models: "lm", "rlm"
MLR_function = "lm"

# Maximum VIF of fitted MLR models to be included
vif_max = lst(
  # vif_max = Inf,
  # vif_max = 1000,
  vif_max = 500
  # vif_max = 100,
  # vif_max = 50,
  # vif_max = 10
)

# Criterion to select best MLR fits, either "rmse" or "aic"
MLR_criterion = "rmse"

# nutrient for cstar calculation
cstar_nutrient = "phosphate"

# Stoichiometric ratio of C to P
rCP = 117

# Stoichiometric ratio of N to P
rNP = 16

# Stoichiometric ratio of P to O (PO4* calculation)
rPO = 170

# Offset P to O (PO4* calculation)
rPO_offset = 1.95

# Preindustrial atmospheric pCO2
preind_atm_pCO2 = 280

# index of slabs to be plotted
plot_slabs = lst(
  plot_slabs = as.factor(c("(26,26.5]", "(27.5,27.75]"))
)

plot_all_figures = "n"

params_local_all <-
  lst(
    slabs_Atl,
    slabs_Ind_Pac,
    MLR_predictors,
    GLODAPv2_version,
    flag_f,
    flag_qc,
    cruises_tco2_calc,
    cruises_talk_calc,
    talk_calc_corr,
    cruises_qc_flag,
    depth_min,
    depth_mapping,
    bottomdepth_min,
    gamma_min,
    CANYON_B_cruise_mean,
    CANYON_B_sample_SD,
    CANYON_B_depth,
    phosphate_corr_316N199,
    talk_corr_316N199,
    tco2_corr_316N199,
    cstar_corr_316N199,
    target_global_rmse_max,
    era_start,
    era_end,
    tref1,
    tref2,
    MLR_basins,
    gap_filling,
    cruises_phosphate_gap_fill,
    cruises_talk_gap_fill,
    cruise_adjustment_relative,
    cruise_adjustment_absolute,
    cstar_deep_sd,
    rarefication,
    rarefication_threshold,
    MLR_target, 
    MLR_predictors_max,
    MLR_predictors_min,
    MLR_number,
    MLR_function,
    vif_max,
    MLR_criterion,
    cstar_nutrient,
    rCP,
    rNP,
    rPO,
    rPO_offset,
    preind_atm_pCO2,
    plot_slabs,
    plot_all_figures
  ) %>%
  cross()



path_root <- "/nfs/kryo/work/jenmueller/emlr_cant/observations"

for (i in 1:length(params_local_all)) {
  # i <- 6
  
  Version_ID <- sprintf("v_1m%02d", i)

  params_local <- nth(params_local_all, i)
  params_local$Version_ID <- Version_ID
  
  # create folder structure
  dir.create(paste(path_root, Version_ID, sep = "/"))
  dir.create(paste(path_root, Version_ID, "data", sep = "/"))
  dir.create(paste(path_root, Version_ID, "website", sep = "/"))
  dir.create(paste(path_root, Version_ID, "figures", sep = "/"))
  dir.create(paste(path_root, Version_ID, "figures/GLODAPv2_2020_subsetting",sep = "/"))
  dir.create(paste(path_root, Version_ID, "figures/Cant_model_sections", sep = "/"))
  dir.create(paste(path_root, Version_ID, "figures/Cruise_sections_histograms", sep = "/"))
  dir.create(paste(path_root, Version_ID, "figures/eMLR_diagnostics", sep = "/"))
  dir.create(paste(path_root, Version_ID, "figures/Observations_correlation", sep = "/"))
  
  # write params_local files
  params_local %>%
    write_rds(file = paste(
      path_root,
      Version_ID,
      "data",
      "params_local.rds",
      sep = "/"
    ))
  
  params_local %>%
    capture.output(file = paste(
      path_root,
      Version_ID,
      "data",
      "params_local.txt",
      sep = "/"
    ))
  
}


```


```{r moving_time_window, eval=FALSE}


path_root <- "/nfs/kryo/work/jenmueller/emlr_cant/observations"

for (i in 0:10) {
  # i <- 0
  
  era_start$era_start <- era_start$era_start + 1
  era_end$era_end <- era_end$era_end + 1
  tref1 <- tref1 + 1
  tref2 <- tref2 + 1
  
  print(i)
  print(era_start)
  print(tref2)
  
  params_local_all <-
    lst(
      slabs_Atl,
      slabs_Ind_Pac,
      MLR_predictors,
      GLODAPv2_version,
      flag_f,
      flag_qc,
      cruises_tco2_calc,
      cruises_talk_calc,
      talk_calc_corr,
      cruises_qc_flag,
      depth_min,
      depth_mapping,
      bottomdepth_min,
      gamma_min,
      CANYON_B_cruise_mean,
      CANYON_B_sample_SD,
      CANYON_B_depth,
      phosphate_corr_316N199,
      talk_corr_316N199,
      tco2_corr_316N199,
      cstar_corr_316N199,
      target_global_rmse_max,
      era_start,
      era_end,
      tref1,
      tref2,
      MLR_basins,
      gap_filling,
      cruises_phosphate_gap_fill,
      cruises_talk_gap_fill,
      cruise_adjustment_relative,
      cruise_adjustment_absolute,
      cstar_deep_sd,
      rarefication,
      rarefication_threshold,
      MLR_target,
      MLR_predictors_max,
      MLR_predictors_min,
      MLR_number,
      MLR_function,
      vif_max,
      MLR_criterion,
      cstar_nutrient,
      rCP,
      rNP,
      rPO,
      rPO_offset,
      preind_atm_pCO2,
      plot_slabs,
      plot_all_figures
    ) %>%
    cross()
  
  
  
  
  
  Version_ID <- sprintf("v_1m%02d", i)
  
  params_local <- nth(params_local_all, 1)
  params_local$Version_ID <- Version_ID
  
  # create folder structure
  dir.create(paste(path_root, Version_ID, sep = "/"))
  dir.create(paste(path_root, Version_ID, "data", sep = "/"))
  dir.create(paste(path_root, Version_ID, "website", sep = "/"))
  dir.create(paste(path_root, Version_ID, "figures", sep = "/"))
  dir.create(paste(
    path_root,
    Version_ID,
    "figures/GLODAPv2_2020_subsetting",
    sep = "/"
  ))
  dir.create(paste(path_root, Version_ID, "figures/Cant_model_sections", sep = "/"))
  dir.create(paste(
    path_root,
    Version_ID,
    "figures/Cruise_sections_histograms",
    sep = "/"
  ))
  dir.create(paste(path_root, Version_ID, "figures/eMLR_diagnostics", sep = "/"))
  dir.create(paste(
    path_root,
    Version_ID,
    "figures/Observations_correlation",
    sep = "/"
  ))
  
  # write params_local files
  params_local %>%
    write_rds(file = paste(path_root,
                           Version_ID,
                           "data",
                           "params_local.rds",
                           sep = "/"))
  
  params_local %>%
    capture.output(file = paste(path_root,
                                Version_ID,
                                "data",
                                "params_local.txt",
                                sep = "/"))
  
}


```



# Create folders

Folders for each new sensitivity run are automatically created.

```{r create_folder_structure, include=FALSE}

path_root           <- "/nfs/kryo/work/jenmueller/emlr_cant/observations"

dir.create(paste(path_root, params_local$Version_ID, sep = "/"))

dir.create(paste(path_root, params_local$Version_ID, "data", sep = "/"))
dir.create(paste(path_root, params_local$Version_ID, "website", sep = "/"))

dir.create(paste(path_root, params_local$Version_ID, "figures", sep = "/"))
dir.create(paste(path_root, params_local$Version_ID, "figures/GLODAPv2_2020_subsetting", sep = "/"))

dir.create(paste(path_root, params_local$Version_ID, "figures/Cant_model_sections", sep = "/"))
dir.create(paste(path_root, params_local$Version_ID, "figures/Cruise_sections_histograms", sep = "/"))
dir.create(paste(path_root, params_local$Version_ID, "figures/eMLR_diagnostics", sep = "/"))
dir.create(paste(path_root, params_local$Version_ID, "figures/Observations_correlation", sep = "/"))


```


# Write file

Parametrisation criteria are locally stored and used throughout this sensitivity case.

```{r write_params_local}

params_local %>%
  write_rds(here::here("data/auxillary",
                       "params_local.rds"))

```


```{r write_params_local_manually, eval=FALSE, include=FALSE}

params_local %>%
  write_rds(file = paste(
    path_root,
    params_local$Version_ID,
    "data",
    "params_local.rds",
    sep = "/"
  ))

params_local %>%
  capture.output(file = paste(
    path_root,
    params_local$Version_ID,
    "data",
    "params_local.txt",
    sep = "/"
  ))

```

